# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-young-violet-auk1e4s4-pooler.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.password=${DB_PASSWORD:npg_jZO6hJWIpBy7}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE/JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true